name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.0.4"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.3"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test:ci

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.0.4"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.3"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist 

  chromatic:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.0.4"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.7.3"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      
