name: Testing On Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: '9.0.4'
      - uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test:ci